###
GET http://localhost:3000/api/menu

###
GET http://localhost:3000/api/menu/5

###
GET http://localhost:3000/api/menu/day/Maanantai


###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "adminpassword"
}

###
POST http://localhost:3000/api/menu
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3MzMzMzEzNTMsImV4cCI6MTczMzQxNzc1M30.hsIQqKWIecHp2ABjPnl_OzGl1TypIGXd2GQB7TTikgo

{
  "nimi": "Lisätty",
  "allerg_id": 1,
  "hinta": 500,
  "day_name": "Perjantai"
}
###
DELETE http://localhost:3000/api/menu/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3MzMzMzEzNTMsImV4cCI6MTczMzQxNzc1M30.hsIQqKWIecHp2ABjPnl_OzGl1TypIGXd2GQB7TTikgo