###

GET http://localhost:3000/api/menu

###
GET http://localhost:3000/api/menu/tilaus

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "adminpassword"
}
###
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyX2xldmVsX2lkIjoxLCJpYXQiOjE3MzMyNDgyODgsImV4cCI6MTczMzMzNDY4OH0.4pxct15R5HTF0D93zejS65kBEhIZ4ePM-c_Ts70FhW0



###
POST http://localhost:3000/api/menu
Content-Type: application/json

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyX2xldmVsX2lkIjoxLCJpYXQiOjE3MzM2ODczNDIsImV4cCI6MTczMzc3Mzc0Mn0.8bYgnmTClI7Or2y4MwmuxjayzH6lYvVG2PENzU6VFrA


{
  "nimi": "Lisätty",
  "allerg_id": 1,
  "hinta": 500,
  "day_name": "Perjantai"
}
###
DELETE http://localhost:3000/api/menu/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3MzMyNDcwMjIsImV4cCI6MTczMzMzMzQyMn0.8qNIs6XEFONhpp56fBu578yk2ADrSYjWnZbgIehVIGQ

###
POST http://localhost:3000/api/menu/tilaus
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyX2xldmVsX2lkIjoxLCJpYXQiOjE3MzM2NzQ5NTIsImV4cCI6MTczMzc2MTM1Mn0.1E-Qinu5b5g0KbXrsG9AntzCvSMfFoSW8DpfJDVJAC0

{
  "user_id":2,
  "tilaukset": [
    {
      "annos_id": 3,
      "määrä": 2
    },
    {
      "annos_id": 4,
      "määrä": 3
    }
  ]
}

### DELETE ALL
DELETE http://localhost:3000/api/menu

###
DELETE http://localhost:3000/api/menu/tilaus/3


###
PUT http://localhost:3000/api/menu/tilaus/1
Content-Type: application/json

{ 
  "tila": "Päivitetty",
  "noutoaika": 3000
 }